### ISSUE TITLE
CONFIG_TARGET_ROOTFS_PARTSIZE自定义不起作用

### ISSUE THREAD

**Issue by drw2005** [281677160/bendi#1]
目前测试的是LEDE源码，其他的还没用过。

新版的默认是下面：
CONFIG_TARGET_KERNEL_PARTSIZE=32
CONFIG_TARGET_ROOTFS_PARTSIZE=600

修改想要的数值后，编译出来的固件仍然是默认的大小。
在固件配置窗口target imgaes里直接修改，出来的也是上面默认的大小。

PS：老版的都没有这个问题。

**Comment by 281677160** [comment]
x86默认最低600的，不足600就自动设置成600，你改700或者以上试试吧，如果用的是ext4固件的话，默认最低是950

**Comment by drw2005** [comment]
> x86默认最低600的，不足600就自动设置成600，你改700或者以上试试吧，如果用的是ext4固件的话，默认最低是950

明白了，谢谢！
