### ISSUE TITLE
# IPV6、IPV4 选择问题请教

### ISSUE THREAD

**Issue by drw2005** [281677160/bendi#3]
# IPV6、IPV4 选择
export Enable_IPV6_function="0"             # 编译IPV6固件(1为启用命令,填0为不作修改)
export Enable_IPV4_function="1"             # 编译IPV4固件(1为启用命令,填0为不作修改)(如果跟IPV6一起开启的话,优先IPV6功能)

看后面的说明看糊涂了，请教：

1、如果两个选项都为1，是分别编译出来两个固件？如果都为0的话是什么结果呢？难道连ipv4都没有了？
改版之前知道想启用ipv6，只要Extra packages --->ipv6helper选上即可

2、现在想启用ipv4和ipv6的话，是两个都是1？还是只把ipv6选择为1就行了？

3、还有这句：如果跟IPV6一起开启的话，优先IPV6功能。 什么叫优先IPV6？那如果我想在启用IPV6的情况下，优先IPV4应该如何设置？

**Comment by 281677160** [comment]
你是第一次编译固件吗？
一次编译能同时编译出2个功能插件不一样的固件？
想编译IPV4功能的就打开Enable_IPV4_function，想编译IPV6的就打开Enable_IPV6_function

有些蛋痛的人喜欢把两项都打开，那就优先Enable_IPV6_function了，就是你编译带IPV6功能的固件

如果是第一次拉取源码编译固件，这些功能都不打开，就是源码默认的呗，源码默认就是IPV4固件，如果你使用了Enable_IPV4_function，那就是在源码默认IPV4的基础下，关闭了几处IPV6的设置而已

因为源码默认的IPV4固件也不全是IPV4的，带一个IPV6选项，不带这个选项，某些插件选择不了的，我本来想在Enable_IPV4_function这里彻底关闭IPV6选项的，又怕人家说怎么XX插件没了啊啥的

如果你的config配置文件里面有IPV6的配置选项了，你想编译IPV4固件，你又不想动手去删除，或者进SSH那么麻烦，你直接打开Enable_IPV4_function，这不是很方便吗？这些开关那么难理解？

**Comment by drw2005** [comment]
> 你是第一次编译固件吗？ 一次编译能同时编译出2个功能插件不一样的固件？ 想编译IPV4功能的就打开Enable_IPV4_function，想编译IPV6的就打开Enable_IPV6_function
> 
> 有些蛋痛的人喜欢把两项都打开，那就优先Enable_IPV6_function了，就是你编译带IPV6功能的固件
> 
> 如果是第一次拉取源码编译固件，这些功能都不打开，就是源码默认的呗，源码默认就是IPV4固件，如果你使用了Enable_IPV4_function，那就是在源码默认IPV4的基础下，关闭了几处IPV6的设置而已
> 
> 因为源码默认的IPV4固件也不全是IPV4的，带一个IPV6选项，不带这个选项，某些插件选择不了的，我本来想在Enable_IPV4_function这里彻底关闭IPV6选项的，又怕人家说怎么XX插件没了啊啥的
> 
> 如果你的config配置文件里面有IPV6的配置选项了，你想编译IPV4固件，你又不想动手去删除，或者进SSH那么麻烦，你直接打开Enable_IPV4_function，这不是很方便吗？这些开关那么难理解？

主要是后面说明把我弄糊涂了，你这一解释明白了，谢谢这么耐心的解释。
