### ISSUE TITLE
第90行else无法执行

### ISSUE THREAD

**Issue by haohaoget** [281677160/bendi#5]
if [[ "${UBUNTU_CODENAME}" =~ (bionic|focal|jammy) ]]; then
  # Nothing to do
else

其中  # Nothing to do改行需要具体代码否则执行报错

**Comment by 281677160** [comment]
感谢，改好了，应该没问题了

**Comment by haohaoget** [comment]
还有一个问题DL下载文件完了检查日志里面是否有error会出错if [[ `grep -ic "ERROR" ${HOME_PATH}/build_logo/build.log` -eq '0' ]]; then因为有个包名 make[2] -C feeds/packages/libs/libgpg-error download里面含有error无法继续编译

**Comment by 281677160** [comment]
> 还有一个问题DL下载文件完了检查日志里面是否有error会出错if [[ `grep -ic "ERROR" ${HOME_PATH}/build_logo/build.log` -eq '0' ]]; then因为有个包名 make[2] -C feeds/packages/libs/libgpg-error download里面含有error无法继续编译

什么源码，什么分支，把配置文件发来，我测试看看

**Comment by haohaoget** [comment]
> > 还有一个问题DL下载文件完了检查日志里面是否有error会出错if [[ `grep -ic "ERROR" ${HOME_PATH}/build_logo/build.log` -eq '0' ]]; then因为有个包名 make[2] -C feeds/packages/libs/libgpg-error download里面含有error无法继续编译
> 
> 什么源码，什么分支，把配置文件发来，我测试看看

lede,master,x86_64配置文件https://raw.githubusercontent.com/haohaoget/build-actions-1/e6688cf1063da7397ff90038f18b065dfce5ff77/build/Lede/seed/x86_64

**Comment by 281677160** [comment]
> > > 还有一个问题DL下载文件完了检查日志里面是否有error会出错if [[ `grep -ic "ERROR" ${HOME_PATH}/build_logo/build.log` -eq '0' ]]; then因为有个包名 make[2] -C feeds/packages/libs/libgpg-error download里面含有error无法继续编译
> > 
> > 
> > 什么源码，什么分支，把配置文件发来，我测试看看
> 
> lede,master,x86_64配置文件https://raw.githubusercontent.com/haohaoget/build-actions-1/e6688cf1063da7397ff90038f18b065dfce5ff77/build/Lede/seed/x86_64

好了
